### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by gbtami** [Solomoriah/PollyReports#1]
Traceback (most recent call last):
  File "polly.py", line 23, in <module>
    rpt.generate(canvas)
  File "/home/tamas/berado/ugyfel/PollyReports.py", line 508, in generate
    self.newpage(canvas, row)
  File "/home/tamas/berado/ugyfel/PollyReports.py", line 401, in newpage
    elementlist = self.pageheader.generate(row)
  File "/home/tamas/berado/ugyfel/PollyReports.py", line 319, in generate
    renderer = element.generate(row)
  File "/home/tamas/berado/ugyfel/PollyReports.py", line 184, in generate
    return Renderer(self, self.pos, self.font, self.gettext(row), self.align,
  File "/home/tamas/berado/ugyfel/PollyReports.py", line 164, in gettext
    value = self.getvalue(row)
  File "/home/tamas/berado/ugyfel/PollyReports.py", line 175, in getvalue
    return self.text.encode('utf8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

The code producing it:

```
# -*- coding: utf-8 -*-

from PollyReports import *
from reportlab.pdfgen.canvas import Canvas

data = ({"firm": "Microsoft", "kontakt": "Bill Gates", "money": 1000000000},
        {"firm": "Szegény Bt.", "kontakt": "Szegény Ödön", "money": 1})

rpt = Report(data)
rpt.detailband = Band([
    Element((0, 0), ("Helvetica", 10), key = "firm"),
    Element((200, 0), ("Helvetica", 10), key = "kontakt"),
    Element((400, 0), ("Helvetica", 10), key = "money"),
])
rpt.pageheader = Band([
    Element((0, 24), ("Helvetica", 10), text = "Cég"),
    Element((200, 24), ("Helvetica", 10), text = "Név"),
    Element((400, 24), ("Helvetica", 10), text = "Pénz"),
    Rule((0, 42), 7.5*72, thickness = 2),
])

canvas = Canvas("polly.pdf")
rpt.generate(canvas)
canvas.save()
```

If I remove the tailing .encode('utf8') from line #175, everything works OK.

**Comment by Solomoriah** [comment]
Ack.  The encode is there to fix a bug that I had.  I wish I knew Unicode better.  For the moment, I'm going to let this ride, but if someone has a suggestion I'd be more than happy to entertain it.

**Comment by gbtami** [comment]
Can you reproduce that bug you mentioned after removing .encode('utf8')?

**Comment by Solomoriah** [comment]
Ack.  I don't remember where I saw it.  It involved pulling data out of MySQL and printing it, but beyond that I don't remember.

For the moment, for your purposes just remove the offending method call.  I'll keep it in mind, and if I can find an example I'll post it.

**Comment by Solomoriah** [comment]
I'm going to close this for now.  I may remove the encode and test it with one of my customers' systems, but I don't have time for that now.
