### ISSUE TITLE
Shapes and backgrounds and other improvements

### ISSUE THREAD

**Issue by therealchalz** [Solomoriah/PollyReports#2]
Hey there,
Great library.  I needed some other functionality so I added it here: https://github.com/therealchalz/PollyReports/commit/6489e3944d651e6cd4e11e8609600d6878163331
The commit message has a fairly comprehensive explanations of the changes.  Some of the changes are backwards compatible, but others are not (eg renaming Element to TextElement).  Maybe if you have a 2.0 in the works you could consider the changes, otherwise let me know if there is specific functionality you want/don't want to keep and I can make an appropriate pull request.

**Comment by Solomoriah** [comment]
I'm going to consider your changes carefully.  I wish you had done this step-by-step, as I can say for sure I won't use some of your changes, but I will want others.  For example, for backward compatibility with my installed versions I will not rename Element or Renderer.  I do like some of the other changes, in particular your text-wrapping changes.  Again, I'm going to look your version over sometime soon.  Thanks for telling me about it!
